### ISSUE TITLE
Filters broken and missing save recipe to list

### ISSUE THREAD

**Issue by linusblom** [chas-academy/09-recipe-book-Ciavarella#2]
The category filter seems to be broken, or not yet implemented as the function only console logs the category.

Also you should be able to save/remove recipes to/from a list.

**Comment by axelolsson** [comment]
@Ciavarella

**Comment by Ciavarella** [comment]
Fixed.

**Comment by axelolsson** [comment]
@linusblom @Ciavarella closing this as the save/remove to list will be added as a part of the next assignment.

I'm confident @Ciavarella understands how to create a rudimentary client-only CRUD operation for recipe lists, in retrospect I probably should've made that part optional for this first assignment and required for the next one.
